#' Add CSI authentication to an interactive Quarto document
#'
#' Call this once inside the server function in `server.R` for a Quarto HTML
#' document or dashboard that uses `server: shiny` and the `csiapps` Quarto
#' extension. It reuses [server_wrapper()] for CSI OAuth and sends the protected
#' report body to the browser only after the session is signed in. Sandbox mode
#' reveals the document locally without contacting CSI authentication.
#' @param protected_body Path to the private body file generated by the Quarto
#'   extension. The default is correct for a standalone document.
#' @param config_file Path to the private runtime configuration generated by the
#'   extension. When present, its institute is applied before OAuth starts.
#' @param sandbox Whether to use the existing csiapps sandbox authentication
#'   behavior. Defaults to [is_sandbox_mode()].
#'
#' @return Invisibly returns `NULL`. The function registers Shiny observers for
#'   the active session.
#' @export
quarto_setup <- function(
    protected_body = ".csiapps-protected-body.html",
    config_file = ".csiapps-quarto.json",
    sandbox = is_sandbox_mode()
  ) {
  session <- shiny::getDefaultReactiveDomain()
  if (is.null(session)) {
    stop("quarto_setup() must be called from an active Shiny session", call. = FALSE)
  }
  runtime_config <- list()
  if (file.exists(config_file)) {
    runtime_config <- jsonlite::fromJSON(config_file, simplifyVector = TRUE)
    if (!is.null(runtime_config$institute) && nzchar(runtime_config$institute)) {
      set_institute(runtime_config$institute)
    }
  }

  initialize <- function(input, output, session) {
    initialized <- shiny::reactiveVal(FALSE)
    session$userData$csiapps_quarto_initialized <- FALSE
    session$userData$csiapps_quarto_observer <- shiny::observe({
      if (!isTRUE(sandbox)) shiny::req(token_ready())
      shiny::req(!initialized())
      if (!file.exists(protected_body)) {
        stop("Protected Quarto body not found: ", protected_body, call. = FALSE)
      }

      body <- paste(readLines(protected_body, warn = FALSE, encoding = "UTF-8"), collapse = "\n")
      session$sendCustomMessage("csiapps_quarto_init", list(
        body = body,
        title = runtime_config$title
      ))
      initialized(TRUE)
      session$userData$csiapps_quarto_initialized <- TRUE
    })
  }

  server_wrapper(
    initialize,
    sandbox = sandbox,
    pause_on_logout = TRUE
  )(session$input, session$output, session)
  invisible(NULL)
}
