#' Add CSI authentication and snapshot data to an interactive Quarto document
#'
#' Call this once from a server-executed cell in a Quarto HTML document or
#' dashboard that uses `server: shiny` and the `csiapps` Quarto extension. It
#' reuses [server_wrapper()] for CSI OAuth and sends the protected report body
#' and registered datasets to the browser only after the session is signed in.
#'
#' @param snapshot_data A zero-argument function returning a named list of
#'   datasets. Each dataset must be a data frame or a list of named records.
#'   The function executes once, after authentication, in the viewer's Shiny
#'   session. Defaults to an empty registry.
#' @param protected_body Path to the private body file generated by the Quarto
#'   extension. The default is correct for a standalone document.
#' @param config_file Path to the private runtime configuration generated by the
#'   extension. When present, its institute is applied before OAuth starts.
#' @param sandbox Whether to use the existing csiapps sandbox authentication
#'   behavior. Defaults to [is_sandbox_mode()].
#'
#' @return Invisibly returns `NULL`. The function registers Shiny observers for
#'   the active session.
#' @export
quarto_setup <- function(
    snapshot_data = function() list(),
    protected_body = ".csiapps-protected-body.html",
    config_file = ".csiapps-quarto.json",
    sandbox = is_sandbox_mode()
  ) {
  if (!is.function(snapshot_data)) {
    stop("snapshot_data must be a zero-argument function", call. = FALSE)
  }

  session <- shiny::getDefaultReactiveDomain()
  if (is.null(session)) {
    stop("quarto_setup() must be called from an active Shiny session", call. = FALSE)
  }
  runtime_config <- list()
  if (file.exists(config_file)) {
    runtime_config <- jsonlite::fromJSON(config_file, simplifyVector = TRUE)
    if (!is.null(runtime_config$institute) && nzchar(runtime_config$institute)) {
      set_institute(runtime_config$institute)
    }
  }

  initialize <- function(input, output, session) {
    initialized <- shiny::reactiveVal(FALSE)
    session$userData$csiapps_quarto_initialized <- FALSE
    session$userData$csiapps_quarto_observer <- shiny::observe({
      shiny::req(token_ready())
      shiny::req(!initialized())
      if (!file.exists(protected_body)) {
        stop("Protected Quarto body not found: ", protected_body, call. = FALSE)
      }

      body <- paste(readLines(protected_body, warn = FALSE, encoding = "UTF-8"), collapse = "\n")
      session$sendCustomMessage("csiapps_quarto_init", list(
        body = body,
        datasets_json = .quarto_datasets_json(snapshot_data()),
        title = runtime_config$title
      ))
      initialized(TRUE)
      session$userData$csiapps_quarto_initialized <- TRUE
    })
  }

  server_wrapper(initialize, sandbox = sandbox)(session$input, session$output, session)
  invisible(NULL)
}

.quarto_datasets_json <- function(datasets) {
  if (!is.list(datasets) || is.data.frame(datasets) ||
      (length(datasets) > 0L && (is.null(names(datasets)) || any(!nzchar(names(datasets)))))) {
    stop("snapshot_data() must return a named list of datasets", call. = FALSE)
  }
  if (length(datasets) == 0L) return("{}")
  if (anyDuplicated(names(datasets))) {
    stop("snapshot dataset names must be unique", call. = FALSE)
  }

  valid <- vapply(datasets, function(dataset) {
    if (is.data.frame(dataset)) return(TRUE)
    if (!is.list(dataset)) return(FALSE)
    if (length(dataset) == 0L) return(TRUE)
    all(vapply(dataset, function(record) is.list(record) && !is.null(names(record)), logical(1)))
  }, logical(1))
  if (!all(valid)) {
    stop(
      "each snapshot dataset must be a data frame or a list of named records: ",
      paste(names(datasets)[!valid], collapse = ", "),
      call. = FALSE
    )
  }

  jsonlite::toJSON(
    datasets,
    dataframe = "rows",
    POSIXt = "ISO8601",
    Date = "ISO8601",
    na = "null",
    null = "null",
    integer64 = "string",
    auto_unbox = TRUE,
    digits = NA,
    force = TRUE
  )
}
